### ISSUE TITLE
zoom problem

### ISSUE THREAD

**Issue by efacin** [kevincobain2000/ionic-photo-browser#5]
when you pinch the image it always zooms to the center, not where you are pinching, is this a known issue, or thats the way it should be? 
the double tap zoom otherwise, works perfectly

**Comment by kevincobain2000** [comment]
hi! I googled a bit and don't think anyone has realized this issue. I ll dig into the code over weekend. Thanks

**Comment by kevincobain2000** [comment]
I think it'd be better to ask this question on [Framework7](https://github.com/nolimits4web/Framework7/issues), we can just update the library to the latest one
